/**
 * This code was generated by Builder.io.
 */
import React from "react";

function AddToCartButton() {
  return (
    <button className="flex overflow-hidden gap-5 justify-between px-3 py-2.5 mt-3.5 text-sm font-medium tracking-tight leading-3 text-purple-800 border border-purple-800 border-solid rounded-[999px] w-full">
      <span className="my-auto">Add to cart</span>
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/04c10f3004c10c1388a9deecfd9c6a15390849c0494f17ec51abefb6ac913cf5?placeholderIfAbsent=true&apiKey=8da3fd6b121a4ce09e18e7d9dae826f0"
        alt=""
        className="object-contain shrink-0 aspect-[1.56] w-[25px]"
      />
    </button>
  );
}

export default AddToCartButton;
