/**
 * This code was generated by Builder.io.
 */
import React from "react";

function Logo() {
  return (
    <div className="flex gap-2.5 text-2xl font-bold text-black whitespace-nowrap">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/8f70a5f3e02f4592d2d3b72e9fed17a6f9b4095cf9c51873905254ade148a3a5?placeholderIfAbsent=true&apiKey=8da3fd6b121a4ce09e18e7d9dae826f0"
        alt="JinStore Logo"
        className="object-contain shrink-0 rounded-none aspect-[1.15] w-[45px]"
      />
      <div>JinStore</div>
    </div>
  );
}

export default Logo;
