/**
 * This code was generated by Builder.io.
 */
import React from "react";

const Navigation = () => {
  return (
    <nav className="flex flex-col justify-center items-center px-16 py-px w-full tracking-tight bg-white max-md:px-5 max-md:max-w-full">
      <div className="flex flex-wrap gap-5 justify-between w-full max-w-[1360px] max-md:max-w-full">
        <div className="flex flex-wrap gap-6 text-base font-semibold leading-3 text-gray-950">
          <div className="flex gap-2 whitespace-nowrap">
            <a href="/" className="my-auto">
              Home
            </a>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/232cf632bb52b42e22986e9263b84dab5dd256297d414b05c56c60c7b825c7ea?placeholderIfAbsent=true&apiKey=8da3fd6b121a4ce09e18e7d9dae826f0"
              className="object-contain shrink-0 w-2.5 aspect-[0.21]"
              alt=""
            />
          </div>
          <div className="flex gap-2.5 whitespace-nowrap">
            <a href="/shop" className="my-auto">
              Shop
            </a>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/94eb986feed028d627debfda425197ac7c570c3215cc776d41844184b697610f?placeholderIfAbsent=true&apiKey=8da3fd6b121a4ce09e18e7d9dae826f0"
              className="object-contain shrink-0 aspect-[0.19] w-[9px]"
              alt=""
            />
          </div>
          <div className="flex gap-7 my-auto">
            <a href="/fruits-vegetables" className="grow">
              Fruits & Vegetables
            </a>
            <a href="/beverages">Beverages</a>
            <a href="/blog">Blog</a>
            <a href="/contact">Contact</a>
          </div>
        </div>
        <div className="flex gap-6">
          <div className="flex gap-3 text-base font-semibold leading-3 text-gray-950">
            <span className="grow my-auto">Trending Products</span>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/022d20f8b35b959dae8bb11fbac10a7497a92c4eee6c29df26c10a7a34b5a6aa?placeholderIfAbsent=true&apiKey=8da3fd6b121a4ce09e18e7d9dae826f0"
              className="object-contain shrink-0 w-2.5 aspect-[0.21]"
              alt=""
            />
          </div>
          <div className="flex gap-2.5 items-center">
            <span className="grow self-stretch my-auto text-base font-semibold leading-3 text-red-600">
              Almost Finished
            </span>
            <span className="self-stretch px-2 py-1.5 my-auto text-xs font-bold leading-none text-center text-white whitespace-nowrap rounded">
              SALE
            </span>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/d0d7f991b7c64d2f189c5be4a082df49f0d19ff57094c107c0da07a067c75f6f?placeholderIfAbsent=true&apiKey=8da3fd6b121a4ce09e18e7d9dae826f0"
              className="object-contain shrink-0 self-stretch w-2.5 aspect-[0.21]"
              alt=""
            />
          </div>
        </div>
      </div>
    </nav>
  );
};

export default Navigation;
