/**
 * This code was generated by Builder.io.
 */
import React from "react";

const StarRating = ({ rating }) => {
  return (
    <div className="flex gap-2 mt-3.5 text-xs tracking-tight leading-none text-gray-500 whitespace-nowrap">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/de54f847bb732b35bbd8cc0dc68766ebc6e3f5c10ac6fe6e21bf34ab42f4aa92?placeholderIfAbsent=true&apiKey=8da3fd6b121a4ce09e18e7d9dae826f0"
        alt=""
        className="object-contain shrink-0 w-full aspect-[6.1]"
      />
      <div>{rating}</div>
    </div>
  );
};

export default StarRating;
